### ISSUE TITLE
Translation of ra.page.list leads to the use of wrong cases

### ISSUE THREAD

**Issue by aucth** [greenbananaCH/ra-language-german#3]
I noticed that the translation of

ra.page.list: 'Liste von %{name}'

leads to the use of wrong german cases. For example: 'Liste von Bücher' instead of 'Liste von Büchern'.

To fix this I would suggest the following translation (or did I miss a feature in polyglot.js??):
ra.page.list: '%{name}'

P.S.: Thanks for the great work

**Comment by langhard** [comment]
You're right. Please create a pull request. I will merge this as soon as possible.

**Comment by langhard** [comment]
Thanks for the pull request!
