### ISSUE TITLE
NPM package is not up to date

### ISSUE THREAD

**Issue by nik-lampe** [greenbananaCH/ra-language-german#5]
Hello,

there are some commits since the last released version on npm. I added this to my project by referencing directly to this git repo. But the current version published on npm would be nice. 🙌🏻

Thanks

**Comment by langhard** [comment]
Sorry I'm late. Was just very busy and couldn't take care of this package. I just released version 2.1.2. Have fun with it. ;-)

**Comment by awesome-manuel** [comment]
Could you update npm to the latest release?

**Comment by DracoBlue** [comment]
@langhard  This would be really great.

**Comment by langhard** [comment]
I have just set up a CI/CD pipeline. So there should be new NPM versions faster in the future. Thank you for your patience.
https://drone.greenbanana.ch/greenbananaCH/ra-language-german/
