### ISSUE TITLE
Prepare new release

### ISSUE THREAD

**Issue by straurob** [greenbananaCH/ra-language-german#8]
Please provide a new release which includes PR #7 so that we can "officially" use it :-)

**Comment by christiaanwesterbeek** [comment]
@langhard A friendly reminder. There are quite a few fixes and translations missing from the current release v2.1.1. Could you please create a new release v2.1.2 and publish to npm?

Check this link to see what's currently missing for folks running `yarn add ra-language-german`:
https://github.com/greenbananaCH/ra-language-german/compare/v2.1.1...master

**Comment by langhard** [comment]
Sorry I'm late. Was just very busy and couldn't take care of this package. I just released version 2.1.2. Have fun with it. ;-)

**Comment by langhard** [comment]
I have just set up a CI/CD pipeline. So there should be new NPM versions faster in the future. Thank you for your patience.
https://drone.greenbanana.ch/greenbananaCH/ra-language-german/
